import 'dart:convert';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:hortijoy_mobile_app/resources/colors.dart';
import 'package:hortijoy_mobile_app/resources/common_navbar.dart';
import 'package:hortijoy_mobile_app/screens/home/components/body.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:hortijoy_mobile_app/screens/login/auth_page.dart';
import 'package:hortijoy_mobile_app/screens/plant_library/components/plant_library_body.dart';
import 'package:hortijoy_mobile_app/screens/planters/components/plant_list_body.dart';
import 'package:hortijoy_mobile_app/screens/shops/components/shops_body.dart';
import 'package:hortijoy_mobile_app/screens/shops/shops.dart';
import 'package:hortijoy_mobile_app/screens/welcome/welcome_screen.dart';
import 'package:hortijoy_mobile_app/screens/add_device_bluetooth/add_device_bluetooth.dart';
import 'package:hortijoy_mobile_app/screens/menu/main_menu.dart';
import 'package:hortijoy_mobile_app/screens/menu/components/main_menu_body.dart';
import 'package:hortijoy_mobile_app/screens/notifications/components/notification_body.dart';
import 'package:hortijoy_mobile_app/screens/planter/planter_profile.dart';

class HomeScreenBody extends StatefulWidget {
  const HomeScreenBody({super.key});

  @override
  State<HomeScreenBody> createState() => _HomeScreenBodyState();
}

class _HomeScreenBodyState extends State<HomeScreenBody> {
  // final _drawerController = ZoomDrawerController();
  int currentIndex = 0;

  @override
  void initState() {
    super.initState();

    // var plantList = [
    //   {
    //     "common_names": ["African Milk Tree", "Cathedral Cactus"],
    //     "botanical_name": ["Euphorbia Trigona"],
    //     "plant_type": ["succulent"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",    
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1678756322028-45eed032ea8f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=627&q=80",
    //     "watering_care_profile_information": "This succulent has specific water requirements, and it's important not to overwater it. Allow the soil to dry out completely between waterings. During the growing season (spring and summer), water more frequently, but still ensure that excess water can drain from the pot to prevent root rot. In the dormant season (fall and winter), reduce watering significantly, as the plant's growth slows down.",
    //     "sunlight_care_profile_information": "Euphorbia trigona thrives in bright, indirect sunlight. Place it near a south or west-facing window where it can receive several hours of bright, filtered light each day. While it can tolerate some direct sunlight, be cautious of too much intense sunlight, as it can scorch the plant.",
    //   },
    //   {
    //     "common_names": [
    //       "African Violet",
    //     ],
    //     "botanical_name": ["Saintpaulia Ionantha"],
    //     "plant_type": ["perennial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": ["spring", "summer"],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/4",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1595609169861-8eedf5d26662?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "African Violets thrive in bright, indirect light. Place them near an east or north-facing window where they can receive gentle morning or filtered light. Avoid exposing them to harsh, direct sunlight, as it can scorch their delicate leaves.",            
    //   },
    //   {
    //     "common_names": [
    //       "Chinese Evergreen",
    //     ],
    //     "botanical_name": ["Aglaonema"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<50",
    //     "light_intensity_sufficient": "50-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "bi-monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "true",
    //     "plant_image_url":"https://images.unsplash.com/photo-1675673428645-6275465791ad?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering. During the growing season (spring and summer), water more frequently, and reduce watering in the dormant period (fall and winter).",
    //     "sunlight_care_profile_information": "Chinese Evergreens are adaptable to a range of light conditions, making them suitable for indoor environments with varying light levels. They can thrive in low to moderate light, but they will have better growth and more vibrant colors with brighter, indirect light. Avoid direct sunlight, as it can scorch their leaves",
    //   },
    //   {
    //     "common_names": ["Elephant's Ear", "African Mask Plant"],
    //     "botanical_name": ["Alocasia"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1642511271386-67d71706ba21?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering. During the growing season (spring and summer), water more frequently, and reduce watering in the dormant period (fall and winter).",
    //     "sunlight_care_profile_information": "Alocasia plants, commonly known as Elephant's Ears, thrive in bright, indirect light. They enjoy plenty of filtered sunlight, but direct sunlight can scorch their leaves. Place them near a window with bright, filtered light.",
    //   },
    //   {
    //     "common_names": [
    //       "Angel Vine",
    //     ],
    //     "botanical_name": ["Muehlenbeckia Complexa"],
    //     "plant_type": ["vine"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://plantsam.com/wp-content/uploads/2015/06/Muehlenbeckia.jpg", 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering. ",
    //     "sunlight_care_profile_information": "Muehlenbeckia complexa plants prefer bright, indirect light. They can tolerate some direct sunlight, especially if it's filtered through a curtain or shade. Too much direct sunlight can lead to leaf scorch. Place your Angel Vine near a window with bright, filtered light.",
    //   },
    //   {
    //     "common_names": [
    //       "Anthurium",
    //       "Tailflower",
    //       "Flamingo Flower",
    //     ],
    //     "botanical_name": ["Anthurium"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-399",
    //     "light_intensity_ideal": "400-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/4",
    //     "has_air_cleaner": "true",
    //     "plant_image_url":"https://images.unsplash.com/photo-1677187458187-d92f24078e4d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "Anthurium plants thrive in bright, indirect light. They can tolerate some direct sunlight, but too much direct sun can scorch their leaves. Place your Anthurium near a window with filtered or diffused light.",
    //   },
    //   {
    //     "common_names": [
    //       "Ming Arailia",
    //     ],
    //     "botanical_name": ["Polyscias Fruticosa"],
    //     "plant_type": ["broadleaf evergreen"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1616500189159-39bd3c378a5e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80", 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "Ming Aralia plants thrive in bright, indirect light. They prefer a location with plenty of filtered sunlight, but avoid exposing them to intense direct sunlight, which can scorch their leaves. Place them near a window with filtered light or in a spot with bright, indirect light.",
    //   },
    //   {
    //     "common_names": [
    //       "Arrowhead Vine",
    //     ],
    //     "botanical_name": ["Syngonium Podophyllum"],
    //     "plant_type": ["vine"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1688370216821-8aba89b95304?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2864&q=80",
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "Arrowhead Vines can tolerate lower light conditions, but their colors and growth will be more vibrant and vigorous with more light. Avoid exposing them to direct sunlight, as it can scorch their leaves. Place them near a window with filtered or diffused light, or a few feet away from a window with bright, indirect light.",
    //   },
    //   {
    //     "common_names": [
    //       "Begonia Rex",
    //       "Angel Wing Begonia",
    //       "Polka Dot Begonia",
    //     ],
    //     "botanical_name": ["Begonia"],
    //     "plant_type": ["topical evergreen", "annual"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1606113345300-32c84150fa1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2906&q=80",
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Most indoor begonias, including Rex Begonias, Angel Wing Begonias, and Polka Dot Begonias, prefer bright, indirect light. They thrive in partial to full shade, making them well-suited for indoor environments away from direct sunlight.",
    //   },
    //   {
    //     "common_names": [
    //       "Wax Begonia",
    //     ],
    //     "botanical_name": ["Begonia Semperflorens"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/4",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://avatars.mds.yandex.net/get-mpic/4448948/img_id7697019295915128220.jpeg/orig",//NONE
    //     "watering_care_profile_information": "Wax Begonias are relatively drought-tolerant, but they prefer even moisture. Allow the top inch (2.5 cm) of the soil to dry out slightly before watering. Avoid water contact with the leaves to prevent fungal issues.",
    //     "sunlight_care_profile_information": "Wax Begonia prefers bright, indirect light to light shade. It can tolerate some direct sunlight, especially during the morning or late afternoon, but avoid exposing it to intense midday sun, which can scorch its leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Bird of Paradise",
    //       "Crane Flower",
    //     ],
    //     "botanical_name": ["Strelitzia Reginae"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "Moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1629271471316-db0ca98807b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Bird of Paradise requires bright, indirect light to thrive. It can tolerate some direct sunlight, especially in the morning or late afternoon, but avoid exposing it to intense midday sun, which can scorch its leaves. Place your Bird of Paradise near a window with filtered or dappled sunlight.",
    //   },
    //   {
    //     "common_names": ["Bromeliad"],
    //     "botanical_name": ["Bromeliaceae Genera"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1665358999033-5f4b2815f827?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "Most bromeliads prefer bright, indirect light. They can tolerate some direct sunlight, especially if it's filtered through a sheer curtain or provided during morning or late afternoon hours. However, avoid intense, midday sunlight, which can scorch their leaves.",
    //   },
    //   {
    //     "common_names":[
    //         "Cactus",
    //         "Finger Jade"]
    //     ,
    //     "botanical_name": ["Crassula Ovata"],
    //     "plant_type": ["succulent"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "medium",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": "",
    //     "fertilizer_frequency": "",
    //     "fertilizer_strength": "",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1519336056116-bc0f1771dec8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out between waterings. During the growing season (spring and summer), water more frequently, and reduce watering in the dormant period (fall and winter).",
    //     "sunlight_care_profile_information": "Crassula ovata 'Gollum,' is a succulent plant that thrives in bright, indirect sunlight. It can tolerate some direct sunlight, especially during the morning or late afternoon hours, but it's best to avoid intense midday sun, which can scorch its leaves. Place your Finger Jade near a window with filtered or diffused light.",
    //   },
    //   {
    //     "common_names": [
    //         "Calathea",
    //         "Zebra Plant",
    //         "Peacock plant"
    //     ],
    //     "botanical_name": ["Calathea"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "true",
    //     "plant_image_url":"https://images.unsplash.com/photo-1581838158095-68d708897c8e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Calathea plants prefer bright, indirect light. They are adapted to the understory of tropical forests and can't tolerate direct sunlight, which can scorch their leaves. Place them near a window with filtered or diffused light, or a few feet away from a window with bright, indirect light",
    //   },
    //   {
    //     "common_names": [
    //       "Calla Lily",
    //     ],
    //     "botanical_name": ["Zantedeschia Aethiopica"],
    //     "plant_type": ["rhizome"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1581838158095-68d708897c8e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Calla Lilies prefer bright, indirect light or filtered sunlight. They can tolerate some direct sunlight, especially during the morning or late afternoon, but avoid exposing them to intense midday sun, as it can scorch their leaves. Place them near a window with bright, diffused light.",
    //   },
    //   {
    //     "common_names": ["Cast Iron Plant"],
    //     "botanical_name": ["Aspidistra Elatior"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<50",
    //     "light_intensity_sufficient": "50-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": ["spring", "summer"],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://www.plantdelights.com/cdn/shop/products/Aspidistra-elatior-Morning-Frost.i-7065.s-66581.r-1_f7eba5b7-59bf-4863-96d5-a678d8f7fb88.jpg?v=1691087732&width=600" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "This plant can thrive in low to moderate light conditions, making it an excellent choice for areas with limited natural light. It can tolerate dim corners and spaces with indirect light. It should be kept away from direct sunlight, as it can scorch its leaves",
    //   },
    //   {
    //     "common_names": ["Coffee Plant"],
    //     "botanical_name": ["Coffea Arabica"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": ["spring", "summer"],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://i.etsystatic.com/18146551/r/il/dbc18b/3648953906/il_1588xN.3648953906_jbo7.jpg" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Place your coffee plant in a spot where it receives bright, indirect light. It can tolerate some morning or late afternoon sun, but avoid exposing it to intense midday sun, which can scorch its leaves.",
    //   },
    //   {
    //     "common_names": ["Cordyline", "Ti Plant"],
    //     "botanical_name": ["Cordyline Terminalis"],
    //     "plant_type": ["everygreen shrub"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1620311626445-672da43b176b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Place your Ti Plant in a location where it receives bright, filtered sunlight. It can tolerate some direct morning or late afternoon sun, but avoid exposing it to intense midday sun, which can scorch its leaves.",
    //   },
    //   {
    //     "common_names": ["Croton"],
    //     "botanical_name": ["Codiaeum Variegatum"],
    //     "plant_type": ["shrub"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "bi-monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1647133653711-6e9d0df97acd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "Crotons require bright, direct sunlight to maintain their vibrant colors. Place them near a window with plenty of sunlight, but protect them from intense midday sun, which can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Sago Palm",
    //       "Cardboard Palm",
    //     ],
    //     "botanical_name": ["Cycas"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1532549872809-c1b33d87e76e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1471&q=80" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "Sago Palms and Cardboard Palms prefer bright, indirect light. They can tolerate some direct sunlight, but avoid exposing them to intense, full sun.",
    //   },
    //   {
    //     "common_names": [
    //       "Desert Rose",
    //     ],
    //     "botanical_name": ["Adenium Obesum"],
    //     "plant_type": ["succulent"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1632813161361-d3a822fd5c26?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1326&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out completely between waterings.",
    //     "sunlight_care_profile_information": "Provide your Desert Rose with plenty of bright, direct sunlight. They thrive in full sun conditions.",
    //   },
    //   {
    //     "common_names": [
    //       "Dieffenchachia",
    //       "Dumb Cane",
    //     ],
    //     "botanical_name": ["dieffenchachia"],
    //     "plant_type": ["tropical perennials"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-399",
    //     "light_intensity_ideal": "400-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "Moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1623910994874-ec52179c9862?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering. ",
    //     "sunlight_care_profile_information": "Dieffenbachia prefers bright, indirect light. Avoid exposing it to direct sunlight, which can scorch the leaves. It can tolerate lower light conditions but may grow more slowly.",
    //   },
    //   {
    //     "common_names": [
    //       "Dracaena",
    //       "Dragon Tree",
    //       "Corn Plant",
    //       "Mass Cane",
    //     ],
    //     "botanical_name": ["Dracaena"],
    //     "plant_type": ["shrub"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1636706574259-ea7b69412b8d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Dracaenas prefer bright, indirect light. Some varieties can tolerate lower light conditions, but they may not thrive in deep shade or intense direct sunlight.",
    //   },
    //   {
    //     "common_names": [
    //       "English Ivy",
    //     ],
    //     "botanical_name": ["Hedra Helix"],
    //     "plant_type": ["perenial", "Evergreen Vine"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url":"https://images.unsplash.com/photo-1542598920-5adc3fbe080c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=710&q=80" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "English Ivy prefers bright, indirect light indoors. Avoid exposing it to intense, direct sunlight for prolonged periods.",
    //   },
    //   {
    //     "common_names": [
    //       "Candelabra Cactus",
    //       "African Candelabra",
    //       "Pencil Cactus",
    //       "Desert Candle",
    //     ],
    //     "botanical_name": ["Euphorbia"],
    //     "plant_type": ["succulent"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1602229925238-c0b238ca4679?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out between waterings as Euphorbias are adapted to arid conditions. ",
    //     "sunlight_care_profile_information": "Most Euphorbia species prefer bright, indirect light.",
    //   },
    //   {
    //     "common_names": [
    //       "Asparagus Fern",
    //     ],
    //     "botanical_name": ["Asparagus Aethiopicus"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.squarespace-cdn.com/content/v1/60a6970e1e471f054b799480/e5f798b1-d882-4655-b644-bcd0b42dd3f9/Asparagus+setaceus+plumosa+fern+02.jpg?format=2500w" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Asparagus fern prefers dappled shade, although it can be acclimated to more light. Keep it out of direct, bright sunlight, which can scorch the foliage.",
    //   },
    //   {
    //     "common_names": [
    //       "Ferns: Asparagus",
    //       "Bird's Nest",
    //       "Boston",
    //       "Button",
    //       "Kangaroo",
    //       "Kimberly Queen",
    //       "Maidenhair",
    //     ],
    //     "botanical_name": ["Asplenium Nidus"],
    //     "plant_type": ["fern"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "true",
    //     "plant_image_url":"https://images.unsplash.com/photo-1615213612138-4d1195b1c0e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "These fern grow well in filtered sunlight to partial shade. Don\'t expose them to direct sunlight other than the very early morning sun.",
    //   },
    //   {
    //     "common_names": [
    //       "Foxtail Fern",
    //     ],
    //     "botanical_name": ["Asparagus Densiflorus"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://www.ottawaflowers.com/cdn/shop/products/plant30.jpg?v=1663971912" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "Indoors, foxtail fern prefers bright, indirect light. It can tolerate some morning sun, but avoid exposing it to intense, direct sunlight.",
    //   },
    //   {
    //     "common_names": [
    //       "Ficus",
    //       "Fiddel Leaf Fig",
    //       "Rubber Plant",
    //       "Weeping Fig",
    //     ],
    //     "botanical_name": ["Ficus"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1619602707513-05a6ef9e3bd1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Keep the soil evenly moist but not soggy. Allow the top inch (2.5 cm) of the soil to dry out before watering.",
    //     "sunlight_care_profile_information": "These species of ficus plants prefer bright indirect light. Avoid harsh direct afternoon sun exposure.",
    //   },
    //   {
    //     "common_names": [
    //       "Fittonias",
    //     ],
    //     "botanical_name": ["Nerve plant", "Mosaic plant"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1600180749315-4d84353283ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow soil surface to dry out between watering.",
    //     "sunlight_care_profile_information": "Fittonias prefer bright indirect light but can tolerate lower light conditions. Place them near a window with filtered or diffused light, or a few feet away from a window with bright, indirect light.",
    //   },
    //   {
    //     "common_names": [
    //       "Gardenia",
    //     ],
    //     "botanical_name": ["Gardenia Jasminoides"],
    //     "plant_type": ["evergreen shrub"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "acid rich fertilizer",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1685669957476-12bbdf277a7d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Gardenias are sensitive to dry soil. Water the plant when the top inch of the soil feels slightly dry. Use room-temperature water to avoid shocking the roots.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Gardenia plant. It appreciates morning sunlight but should be protected from intense afternoon sun.",
    //   },
    //   {
    //     "common_names": [
    //       "Ginseng Ficus",
    //       "Indian Laurel",
    //     ],
    //     "botanical_name": ["Ficus Bonsai"],
    //     "plant_type": ["bonsai", "tree"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1512428813834-c702c7702b78?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Water the plant when the top inch of the soil feels slightly dry. Be cautious not to overwater, as Ficus bonsai are susceptible to root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Ficus bonsai. It can tolerate some direct sunlight, but avoid intense midday sun, especially during the hottest months. Rotate the plant periodically to ensure even growth.",
    //   },
    //   {
    //     "common_names": [
    //       "Homalomena",
    //     ],
    //     "botanical_name": ["Homalomena"],
    //     "plant_type": ["evergreen perenial"],
    //     "light_intensity_dark": "<50",
    //     "light_intensity_sufficient": "50-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1660458528345-52f07255bb81?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Water the plant when the top inch of the soil feels slightly dry. Avoid letting the plant sit in standing water.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Homalomena plant. It can tolerate lower light conditions, but it will display its best coloration and patterns in moderate to bright, filtered light.",
    //   },
    //   {
    //     "common_names": [
    //       "Wax Plant",
    //     ],
    //     "botanical_name": ["Hoya Carnosa"],
    //     "plant_type": ["vine succulent"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1658508947279-eec7838232b9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch or so of the soil to dry out between waterings. Water thoroughly when the soil feels dry. Wax Plants are somewhat drought-tolerant and prefer to dry out a bit between waterings.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Wax Plant. It can tolerate some morning or evening sunlight, but avoid intense midday sun.",
    //   },
    //   {
    //     "common_names": [
    //       "Polka Dot Plant",
    //     ],
    //     "botanical_name": ["Hypoestes Phyllostachya"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1677612680321-7c63f32127ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Water the plant when the top inch of the soil feels slightly dry. Avoid letting the plant sit in standing water.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Polka Dot Plant. It can tolerate some lower light conditions, but it will display its best coloration and patterns in bright, filtered light. Avoid direct sunlight, which can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "White Jasmine",
    //       "Pink Jasmine",
    //       "Chinese Jasmine",
    //     ],
    //     "botanical_name": ["Jasminum Polyanthum"],
    //     "plant_type": ["perenial vine"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1549994140-717e13478ff4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Water the plant thoroughly when the top inch of the soil feels slightly dry. During active growth, it may need more frequent watering.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Jasmine plant. It can tolerate some direct morning sunlight, but avoid intense afternoon sun.",
    //   },
    //   {
    //     "common_names": [
    //       "Kalanchoe",
    //     ],
    //     "botanical_name": ["Kalanchoe"],
    //     "plant_type": ["perenial", "succulent"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1663534978362-4cffa1ed0a3d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out between waterings. Water thoroughly when the top inch or so of the soil feels dry. Avoid overwatering, as Kalanchoes are susceptible to root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Kalanchoe plant. They can tolerate some direct sunlight, especially morning sunlight, but avoid intense afternoon sun.",
    //   },
    //   {
    //     "common_names": [
    //       "Prayer Plant",
    //     ],
    //     "botanical_name": ["Maranta Leuconeura"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1639756534497-d3271888337c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not soggy. Water when the top inch or so of the soil feels dry. Avoid letting the plant sit in standing water.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Prayer Plant. It can tolerate some lower light conditions, but it will display its best color and patterns in bright, filtered light. Avoid direct sunlight, which can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Money Tree",
    //     ],
    //     "botanical_name": ["Pachira Aquatica"],
    //     "plant_type": ["tree"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1633789242668-886f4098ea1c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch or so of the soil to dry out between waterings. Water thoroughly and ensure proper drainage to prevent root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Money Tree. It can tolerate some lower light conditions, but it will thrive in brighter light. Avoid direct sunlight, as it can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Monstera",
    //       "Swiss Cheese Plant",
    //     ],
    //     "botanical_name": ["Monstera"],
    //     "plant_type": ["climbing evergreen"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-399",
    //     "light_intensity_ideal": "400-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1628620223412-ad52eef8c4de?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=686&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch or so of the soil to dry out between waterings. Water thoroughly and ensure proper drainage to prevent root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Monstera. It can tolerate some lower light conditions, but it will thrive and develop more fenestrations in brighter light. Avoid direct sunlight, as it can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Norfolk Island Pine",
    //     ],
    //     "botanical_name": ["Araucaria Heterophylla"],
    //     "plant_type": ["tree"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "medium",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://planterina.com/cdn/shop/files/Norfolk-Island-Pine-Plant-Care_632bb039-e340-4075-a31e-cd6ffe623de9_2000x.jpg?v=1657497672" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow the top inch of soil to dry out slightly before watering. Avoid letting the plant sit in standing water.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Norfolk Island Pine. It can tolerate some direct sunlight, especially in the morning or evening, but too much direct sun can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Areca Palm",
    //       "Bamboo Palm",
    //       "Chinese Fan Palm",
    //       "Sago Palm",
    //       "Majesty Palm",
    //     ],
    //     "botanical_name": ["Arecaceae"],
    //     "plant_type": ["palm or cycad(bright indirect light)"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1598531403144-43fdb36c9ae8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch or so of the soil to dry out between waterings. Water thoroughly and ensure proper drainage.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light. Different palm species tolerate varying light conditions, but bright, filtered light is generally ideal.",
    //   },
    //   {
    //     "common_names": [
    //       "Parlor Palm", 
    //       "Cascade Palm", 
    //       "Cat Palm", 
    //       "Kentia Palm"
    
    //     ],
    //     "botanical_name": ["Chamaedorea Elegans", "Chamaedorea Cataractarum"],
    //     "plant_type": ["palm (low light)"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-399",
    //     "light_intensity_ideal": "400-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1687269111857-3b398711c2f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch or so of the soil to dry out between waterings. Water thoroughly and ensure proper drainage to prevent root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your palm plants. They can tolerate lower light conditions, but they will do best in bright, filtered light. Avoid direct sunlight, which can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Peace Lily",
    //     ],
    //     "botanical_name": ["Spathiphyllum"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-399",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1685430488624-e5971910cba4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80" , 
    //     "watering_care_profile_information": "Water the plant when the top inch of the soil feels dry. Keep the soil consistently moist but not soggy. Overwatering can lead to root rot, so ensure proper drainage.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Peace Lily. While it can tolerate lower light conditions, it will produce more flowers in brighter light. Avoid direct sunlight, as it can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Peperomia",
    //     ],
    //     "botanical_name": ["Peperomia"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-399",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1610630876605-97b3e670f56c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch of the soil to dry out between waterings. Water the plant thoroughly, but avoid overwatering to prevent root rot.",
    //     "sunlight_care_profile_information": "Peperomias prefer bright, indirect light. They can tolerate lower light conditions, but too much direct sunlight can scorch their leaves.",
    //   },
    //   {
    //     "common_names": ["Phalaenopsis Orchid", "Moth Orchid"],
    //     "botanical_name": ["Phalaenopsis"],
    //     "plant_type": ["herbaceous", "perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "need orchid fertilizer",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":"https://images.unsplash.com/photo-1649149181324-8d4af4d0d79c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80" , 
    //     "watering_care_profile_information": "Watering frequency depends on factors such as humidity, temperature, and potting mix. Water thoroughly when the top inch of the potting mix feels dry. It's better to underwater slightly than overwater.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Phalaenopsis orchid. Avoid direct sunlight, as it can burn the leaves. A north- or east-facing window is often ideal.",
    //   },
    //   {
    //     "common_names": [
    //       "Philodendron Vine: Heartleaf",
    //       "Philodendron Vine: Basil",
    //     ],
    //     "botanical_name": ["Philodendron"],
    //     "plant_type": ["perenial vine"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1624622434922-ab4f0662fb74?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch of the soil to dry out between waterings. Water thoroughly and avoid overwatering to prevent root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Heartleaf Philodendron. It can tolerate lower light conditions, but it thrives in bright, filtered light.",
    //   },
    //   {
    //     "common_names": [
    //       "Philodendrons climbing/self-heading variety: Tree",
    //       "Moonlight",
    //       "Imperial Red",
    //       "Prince of Orange",
    //       "Pink Princess",
    //     ],
    //     "botanical_name": ["Philodendron"],
    //     "plant_type": ["broadleaf evergreen"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "low",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1644996649400-f19889c8a4ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80" , 
    //     "watering_care_profile_information": " Allow the top inch of the soil to dry out between waterings. Water thoroughly and avoid overwatering to prevent root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Heartleaf Philodendron. It can tolerate lower light conditions, but it thrives in bright, filtered light.",
    //   },
    //   {
    //     "common_names": [
    //       "Aluminum Plant",
    //       "Cadierei",
    //       "Money Plant",
    //     ],
    //     "botanical_name": ["Pilea"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1687810829027-4ccf6fdaa59e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1471&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not soggy. Allow the top inch of the soil to dry out between waterings. Avoid overwatering, as it can lead to root rot.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for your Aluminum Plant. Avoid direct sunlight, as it can scorch the leaves. Bright, filtered light is ideal.",
    //   },
    //   {
    //     "common_names": [
    //       "Pony Tail Palm",
    //     ],
    //     "botanical_name": ["Beaucarnea Recurvata"],
    //     "plant_type": ["broadleaf evergreen"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1612881073328-735a582c73f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out completely between waterings. Water sparingly and avoid overwatering, as the plant is adapted to dry conditions. Water less frequently during the dormant winter months.",
    //     "sunlight_care_profile_information": "Provide bright, indirect sunlight for indoor Ponytail Palms. They can tolerate some direct sunlight, especially if gradually acclimated. Outdoors, they prefer partial to full sun.",
    //   },
    //   {
    //     "common_names": [
    //       "Pothos",
    //     ],
    //     "botanical_name": ["Epipremnum Aureum"],
    //     "plant_type": ["vine"],
    //     "light_intensity_dark": "<50",
    //     "light_intensity_sufficient": "50-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1595524147656-eb5d0a63e9a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch or so of the soil to dry out between waterings. Water thoroughly, and make sure the pot has good drainage to prevent overwatering.",
    //     "sunlight_care_profile_information": "Pothos can tolerate a wide range of light conditions. It thrives in indirect or filtered light, but it can also tolerate lower light conditions. Avoid direct sunlight, as it can lead to sunburn and fading of variegation",
    //   },
    //   {
    //     "common_names": [
    //       "Purple Waffle Plant",
    //       "Red Ivy",
    //     ],
    //     "botanical_name": ["Hemigraphis Alternata"],
    //     "plant_type": ["perenial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://tropicalsprouts.com/cdn/shop/products/il_1140xN.3967788506_77q9.webp?v=1666579297&width=713" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist, but avoid overwatering. Ensure proper drainage to prevent root rot. Water when the top inch of soil feels slightly dry.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for the Purple Waffle Plant. While it can tolerate lower light conditions, it will display its most vibrant colors in bright light.",
    //   },
    //   {
    //     "common_names": [
    //       "Snake Plant",
    //     ],
    //     "botanical_name": ["Dracaena Trifasciata", "Sansevieria"],
    //     "plant_type": ["evergreen", "perennial"],
    //     "light_intensity_dark": "<50",
    //     "light_intensity_sufficient": "50-199",
    //     "light_intensity_ideal": ">200",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "low",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1687552212914-03a30c82053c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=715&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out completely between waterings. Water sparingly and avoid overwatering, as Snake Plants are susceptible to root rot. It's better to underwater than to keep the soil consistently moist.",
    //     "sunlight_care_profile_information": "Snake Plants tolerate a wide range of light conditions. They can survive in low light, but they will grow best in bright, indirect light. Avoid exposing them to direct sunlight, as it can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Schefflera",
    //       "Umbrella Plant",
    //       "Umbrella Tree",
    //     ],
    //     "botanical_name": ["Schefflera"],
    //     "plant_type": ["Schefflera arboricola"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1602229924961-ce7e191c375c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80" , 
    //     "watering_care_profile_information": "Allow the top inch of the soil to dry out before watering. Water the plant thoroughly and allow excess water to drain from the bottom of the pot. Avoid letting the plant sit in standing water.",
    //     "sunlight_care_profile_information": "Schefflera plants prefer bright, indirect light. They can tolerate some direct sunlight, but too much intense light can lead to leaf burning. If kept indoors, place them near a window with filtered sunlight",
    //   },
    //   {
    //     "common_names": [
    //       "Christmas Cactus",
    //       "Thanksgiving Cactus",
    //       "Easter Cactus",
    //     ],
    //     "botanical_name": ["Schlumbergera", "Rhipsalidopsis"],
    //     "plant_type": ["succulent", "cactus", "perennial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url": "https://images.unsplash.com/photo-1663472885393-dd50182b5535?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not soggy. Water the plant when the top inch of the soil feels slightly dry. Avoid letting the plant sit in standing water.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for Christmas Cacti. Avoid direct sunlight, as it can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Spider Plant",
    //     ],
    //     "botanical_name": ["Chlorophytum Comosum"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "true",
    //     "plant_image_url": "https://images.unsplash.com/photo-1647631703143-a7d8dc552c8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out partially between waterings. Water the plant thoroughly when the top inch of the soil feels dry. Spider Plants are fairly forgiving if you occasionally forget to water them.",
    //     "sunlight_care_profile_information": "Spider Plants prefer bright, indirect light. They can tolerate some direct sunlight, but too much sun can scorch their leaves. ",
    //   },
    //   {
    //     "common_names": [
    //       "Stromanthe",
    //     ],
    //     "botanical_name": ["Stromanthe"],
    //     "plant_type": ["tropical perennial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1687166752260-c423a780289b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Water the plant when the top inch of the soil feels slightly dry. Mist the leaves regularly to maintain humidity.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for Stromanthe plants. They prefer filtered sunlight or a location with some shade to prevent direct sun exposure that could scorch their leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Jade Plant",
    //     ],
    //     "botanical_name": ["Crassula Ovata"],
    //     "plant_type": ["succulent"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "partial dry",
    //     "water_status_percentage": "20",
    //     "standard_water_profile_status": "medium",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1616189597001-9046fce2594d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out partially between waterings. Water the plant thoroughly when the top inch of the soil feels dry. Overwatering can lead to root rot, so it's better to underwater than overwater.",
    //     "sunlight_care_profile_information": "Provide bright, indirect sunlight for optimal growth. Jade plants can tolerate some direct sunlight, but be cautious not to expose them to too much intense sunlight, as it can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "Succulent",
    //     ],
    //     "botanical_name": ["Succulent"],
    //     "plant_type": ["succulent"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out completely between waterings. Overwatering is a common issue for succulents, as they are adapted to survive in dry conditions. Water sparingly but thoroughly.",
    //     "sunlight_care_profile_information": "Most succulents thrive in bright, direct sunlight. However, some species can tolerate lower light conditions. It's important to find the right balance for each type of succulent.",
    //   },
    //   {
    //     "common_names": [
    //       "Aloe Vera",
    //     ],
    //     "botanical_name": ["Aloe Vera"],
    //     "plant_type": ["succulent"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "true",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80" , 
    //     "watering_care_profile_information": "Allow the soil to dry out completely between waterings. Overwatering can lead to root rot, so it's better to underwater than overwater.",
    //     "sunlight_care_profile_information": "Aloe vera prefers bright, indirect sunlight. It can tolerate some direct sunlight, especially if it's gradually acclimated to prevent sunburn.",
    //   },
    //   {
    //     "common_names": ["Spiderwort", "Inch Plant"],
    //     "botanical_name": ["Tradescantias"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "bi-monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1641906030021-e97372fce30f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1373&q=80" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not waterlogged. Allow the top inch of soil to dry out between waterings. Avoid letting the plant sit in standing water.",
    //     "sunlight_care_profile_information": "Tradescantias prefer bright, indirect light. They can tolerate some direct sunlight, but too much direct sun can scorch their leaves",
        
    //   },
    //   {
    //     "common_names": [
    //       "Yucca",
    //     ],
    //     "botanical_name": ["Yucca"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<400",
    //     "light_intensity_sufficient": "400-800",
    //     "light_intensity_ideal": ">800",
    //     "light_intensity_too_sunny": "",
    //     "standard_light_intensity": "bright",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "low",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1585738876562-7d008f53022a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=690&q=80" , 
    //     "watering_care_profile_information": "Yucca plants are drought-tolerant and prefer well-draining soil. Allow the soil to dry out between waterings. Overwatering can lead to root rot.",
    //     "sunlight_care_profile_information": "Yuccas prefer bright, direct sunlight. They can tolerate full sun and thrive in outdoor settings with plenty of sunlight exposure.",
    //   },
    //   {
    //     "common_names": ["Elephant's Ear"],
    //     "botanical_name": ["Xanthosoma"],
    //     "plant_type": ["herbaceous", "perennial"],
    //     "light_intensity_dark": "<200",
    //     "light_intensity_sufficient": "200-399",
    //     "light_intensity_ideal": "400-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://api.floriday.io/images/d29e7c7e-a36b-4aa2-8c7a-e7c9c029a237.jpg" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist, but not waterlogged. Ensure proper drainage to prevent root rot. Water when the top inch of soil feels slightly dry.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light for Xanthosoma plants. They can tolerate some direct sunlight, especially if the leaves are acclimated gradually to prevent sunburn.",
    //   },
    //   {
    //     "common_names": [
    //       "Zebra Plant",
    //     ],
    //     "botanical_name": ["Aphelandra Squarrosa"],
    //     "plant_type": ["annual"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-800",
    //     "light_intensity_too_sunny": ">800",
    //     "standard_light_intensity": "low",
    //     "water_status": "moist",
    //     "water_status_percentage": "30",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //     ],
    //     "fertilizer_frequency": "bi-weekly",
    //     "fertilizer_strength": "1",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://dk-nn.ru/800/600/https/www.grupohijuelas.cl/wp-content/uploads/2018/02/Aphelandra_m24-1.jpg" , 
    //     "watering_care_profile_information": "Keep the soil consistently moist but not soggy. Water the plant when the top inch of the soil feels slightly dry. Use room temperature water to avoid shocking the plant.",
    //     "sunlight_care_profile_information": "Provide bright, indirect light to your Aphelandra plant. Avoid direct sunlight, as it can scorch the leaves.",
    //   },
    //   {
    //     "common_names": [
    //       "ZZ Plant",
    //     ],
    //     "botanical_name": ["Zamioculcas Zamiifolia"],
    //     "plant_type": ["perennial"],
    //     "light_intensity_dark": "<100",
    //     "light_intensity_sufficient": "100-199",
    //     "light_intensity_ideal": "200-1000",
    //     "light_intensity_too_sunny": ">1000",
    //     "standard_light_intensity": "low",
    //     "water_status": "dry",
    //     "water_status_percentage": "10",
    //     "standard_water_profile_status": "high",
    //     "fertilizer_season": [
    //       "spring",
    //       "summer",
    //       "fall",
    //     ],
    //     "fertilizer_frequency": "bi-monthly",
    //     "fertilizer_strength": "1/2",
    //     "has_air_cleaner": "false",
    //     "plant_image_url":
    //         "https://images.unsplash.com/photo-1614594895304-fe7116ac3b58?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    //     "watering_care_profile_information": "One of the most important aspects of ZZ plant care is to avoid overwatering. These plants have rhizomes that store water, allowing them to withstand drought conditions. Water the plant when the top inch or so of the soil is dry. It's better to underwater than overwater, as the plant can rot if the soil remains too wet.",
    //     "sunlight_care_profile_information": "ZZ plants can tolerate low-light conditions, making them ideal for areas with limited natural light. However, they can also adapt to brighter indirect light. Direct sunlight should be avoided as it can scorch the leaves. ",
    //   },
    // ];

    // plantList.forEach((element) async {
    //   await FirebaseFirestore.instance
    //       .collection("plant_library_test_first")
    //       .add({
    //     "botanical_name": jsonEncode(element["botanical_name"]),
    //     "common_names": jsonEncode(element["common_names"]),
    //     "fertilizer_frequency": element["fertilizer_frequency"].toString(),
    //     "fertilizer_season": element["fertilizer_season"].toString(),
    //     "fertilizer_strength": element["fertilizer_strength"].toString(),
    //     "has_air_cleaner": element["has_air_cleaner"].toString(),
    //     "light_intensity_dark": element["light_intensity_dark"].toString(),
    //     "light_intensity_ideal": element["light_intensity_ideal"].toString(),
    //     "light_intensity_sufficient":
    //         element["light_intensity_sufficient"].toString(),
    //     "light_intensity_too_sunny":
    //         element["light_intensity_too_sunny"].toString(),
    //     "plant_image_url": element["plant_image_url"].toString(),
    //     "plant_type": jsonEncode(element["plant_type"]),
    //     "standard_light_intensity":
    //         element["standard_light_intensity"].toString(),
    //     "standard_water_profile_status":
    //         element["standard_water_profile_status"].toString(),
    //     "water_status": element["water_status"].toString(),
    //     "water_status_percentage": element["water_status_percentage"].toString(),
    //     "watering_care_profile_information": element["watering_care_profile_information"].toString(),
    //     "sunlight_care_profile_information": element["sunlight_care_profile_information"].toString()
    //   });
    // });
  
  }

  @override
  void dispose() {
    super.dispose();
  }

  void signUserOut() {
    FirebaseAuth.instance.signOut();
    Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => WelcomeScreen(),
        ));
  }

  @override
  Widget build(BuildContext context) {
    return currentScreen();
  }

  Widget currentScreen() {
    if (currentIndex == 5) {
      signUserOut();
    } else {
      switch (currentIndex) {
        case 0:
          return Body();
        case 1:
          return PlantLibraryBody(
            selectedFilters: [],
          );
        case 2:
          return PlantListBody();
        case 3:
          return ShopsBody();
        case 4:
          return NotificationBody(
            selectedFilters: [],
          );
        default:
          return Body();
      }
    }
    return AuthPage();
  }
}
