// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwsCOcyYHPH9XMx_uMDK9knUMrs6TL-8',
    appId: '1:320515886578:web:2f64b6c609a67fe8d06f6b',
    messagingSenderId: '320515886578',
    projectId: 'hortijoy-staging',
    authDomain: 'hortijoy-staging.firebaseapp.com',
    databaseURL:
        'https://hortijoy-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hortijoy-staging.appspot.com',
    measurementId: 'G-TDV3MX8KLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1u-7kEVBnnOAilQynS_0_2UsGyE25wrc',
    appId: '1:320515886578:android:fc5b745035014498d06f6b',
    messagingSenderId: '320515886578',
    projectId: 'hortijoy-staging',
    databaseURL:
        'https://hortijoy-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hortijoy-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfi_0-SzuJBmj4FYca-8BAkupM5egic8o',
    appId: '1:320515886578:ios:26aa46e888026fe8d06f6b',
    messagingSenderId: '320515886578',
    projectId: 'hortijoy-staging',
    databaseURL:
        'https://hortijoy-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hortijoy-staging.appspot.com',
    iosClientId:
        '320515886578-v0mqq6p4j117skv108mgfm568q1fhgkc.apps.googleusercontent.com',
    iosBundleId: 'com.hortijoy.hortijoy',
  );
}
