import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppThemeLightAppBar extends AppBar {
  AppThemeLightAppBar({
    Key? key,
    Widget? leading,
    bool? automaticallyImplyLeading = true,
    Widget? title,
    List<Widget>? actions,
    Widget? flexibleSpace,
    PreferredSizeWidget? bottom,
    double? elevation,
    Color? shadowColor,
    ShapeBorder? shape,
    Color? backgroundColor,
    Color? foregroundColor,
    Brightness? brightness,
    IconThemeData? iconTheme,
    IconThemeData? actionsIconTheme,
    TextTheme? textTheme,
    bool? primary = true,
    bool? centerTitle,
    bool? excludeHeaderSemantics = false,
    double? titleSpacing,
    double toolbarOpacity = 1.0,
    double bottomOpacity = 1.0,
    double? toolbarHeight,
    // uses 56.0 as standard,
    // 56 + 20px = 76px
    double? leadingWidth,
    bool? backwardsCompatibility,
    TextStyle? toolbarTextStyle,
    TextStyle? titleTextStyle,
    SystemUiOverlayStyle? systemOverlayStyle,
  }) : super(
            key: key,
            actions: actions,
            actionsIconTheme: actionsIconTheme,
            automaticallyImplyLeading: automaticallyImplyLeading ?? false,
            backgroundColor: backgroundColor,
            backwardsCompatibility: backwardsCompatibility,
            bottom: bottom,
            bottomOpacity: bottomOpacity,
            brightness: brightness,
            centerTitle: centerTitle,
            elevation: elevation,
            excludeHeaderSemantics: excludeHeaderSemantics ?? false,
            flexibleSpace: flexibleSpace,
            foregroundColor: foregroundColor,
            iconTheme: iconTheme,
            leading: leading,
            leadingWidth: leadingWidth,
            primary: primary ?? false,
            shadowColor: shadowColor,
            shape: shape,
            systemOverlayStyle: systemOverlayStyle,
            textTheme: textTheme,
            title: title,
            titleSpacing: titleSpacing,
            titleTextStyle: titleTextStyle,
            toolbarHeight: toolbarHeight,
            toolbarOpacity: toolbarOpacity,
            toolbarTextStyle: toolbarTextStyle);
}
